package com.yacht.restriction.constant;

public enum ConditionType {
    EQUALS,
    IN,
    NOT_IN,
    LESS_THAN_OR_EQUAL_TO,
    LESS_THAN_NOT_EQUAL_TO,
    GREATER_THAN_OR_EQUAL_TO,
    GREATER_THAN_NOT_EQUAL_TO,
    IS_NULL,
    IS_NOT_NULL,
    NOT_EQUAL,
    LIKE,
    ILIKE,
    NOT_LIKE,
    NOT_ILIKE,
    BETWEEN,
    EQUAL_PROPERTY,
    NOT_EQUAL_PROPERTY,
    STR_IN,
    EQUALS_TRIM,
    NOT_EQUALS_TRIM,
    IS_EMPTY,
    IS_NOT_EMPTY,
}
